services:
  a2rl:
    image: a2rl
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerostack2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      TERM: $TERM
      SHELL: $SHELL
      ROS_LOCALHOST_ONLY: 0
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    privileged: true
    restart: always
    volumes:
      # display related 
      - ~/.Xauthority:/root/.Xauthority:rw
      # ssh related
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # nvim related
      - ~/.config/nvim:/root/.config/nvim:rw
      - ~/.config/coc:/root/.config/coc:rw
      - ~/.config/github-copilot:/root/.config/github-copilot:rw
      - ~/.local/share/nvim/:/root/.local/share/nvim/:rw
      # tmux related
      - ~/.tmux:/root/.tmux:ro
      - ~/.tmux.conf:/root/.tmux.conf:ro
      # git
      - ~/.gitconfig:/root/.gitconfig_local
      # working dirs
      - ./workspace:/root/aerostack2_ws/:rw
      # dev
      - /dev:/dev:rw
      # rosbag
      - ~/a2rl_rosbags:/root/a2rl_rosbags:rw
    network_mode: "host"
    command: tail -f /dev/null
