#[apt] Installation commands:
  apt-get install ros-humble-rclpy -y 
  apt-get install ros-humble-ament-copyright -y 
  apt-get install ros-humble-ament-flake8 -y 
  apt-get install ros-humble-ament-pep257 -y 
  apt-get install python3-pytest -y 
  apt-get install ros-humble-behaviortree-cpp-v3 -y 
  apt-get install ros-humble-nav2-behavior-tree -y 
  apt-get install ros-humble-nav2-msgs -y 
  apt-get install ros-humble-rclcpp -y 
  apt-get install ros-humble-rclcpp-action -y 
  apt-get install ros-humble-std-srvs -y 
  apt-get install ros-humble-geometry-msgs -y 
  apt-get install ros-humble-sensor-msgs -y 
  apt-get install ros-humble-ament-lint-auto -y 
  apt-get install ros-humble-ament-lint-common -y 
  apt-get install ros-humble-ament-cmake -y 
  apt-get install ros-humble-std-msgs -y 
  apt-get install libeigen3-dev -y 
  apt-get install libncurses5-dev -y 
  apt-get install ros-humble-ament-cmake-clang-format  -y 
  apt-get install ros-humble-ament-cmake-cppcheck -y 
  apt-get install ros-humble-ament-cmake-cpplint -y 
  apt-get install ros-humble-nav-msgs -y 
  apt-get install ros-humble-librealsense2 -y 
  apt-get install ros-humble-tf2 -y 
  apt-get install ros-humble-tf2-ros -y 
  apt-get install ros-humble-pluginlib -y 
  apt-get install ros-humble-rclcpp-components -y 
  apt-get install ros-humble-rosidl-default-generators -y 
  apt-get install ros-humble-builtin-interfaces -y 
  apt-get install ros-humble-geographic-msgs -y 
  apt-get install ros-humble-action-msgs -y 
  apt-get install ros-humble-rosidl-default-runtime -y 
  apt-get install python3-pymap3d -y 
  apt-get install python3-pydantic -y 
  apt-get install ros-humble-gazebo-ros-pkgs -y 
  apt-get install python3-jinja2 -y 
  apt-get install ros-humble-rclcpp-lifecycle -y 
  apt-get install ros-humble-tf2-geometry-msgs -y 
  apt-get install ros-humble-image-transport -y 
  apt-get install ros-humble-cv-bridge -y 
  apt-get install libgeographic-dev -y 
  apt-get install libyaml-cpp-dev -y 
  apt-get install ros-humble-ament-cmake-gtest -y 
  apt-get install ros-humble-trajectory-msgs -y 
  apt-get install ros-humble-visualization-msgs -y 
  apt-get install libusb-1.0-0 -y 
  apt-get install libusb-1.0-0-dev -y 
  apt-get install ros-humble-ament-cmake-python -y 
  apt-get install libbenchmark-dev -y 
  apt-get install ros-humble-ros-gz-sim -y 
  apt-get install ros-humble-ros-gz-bridge -y 
  apt-get install ros-humble-tf2-msgs -y 
  apt-get install ros-humble-ament-cmake-pytest -y 
