services:
  {{ project_name }}:
    image: {{ project_name }}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{ project_name }}
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      TERM: $TERM
      SHELL: $SHELL
    {{ % if gpu % }}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    {{ % endif % }}
      ROS_LOCALHOST_ONLY: 1
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    {{ % if gpu % }}
    runtime: nvidia
    {{ % endif % }}
    {{ % if privileged % }}
    privileged: true
    {{ % endif % }}
    restart: always
    volumes:
      # display related 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # nvim related
      - ~/.config/nvim:/root/.config/nvim:rw
      - ~/.config/coc:/root/.config/coc:rw
      - ~/.config/github-copilot:/root/.config/github-copilot:rw
      - ~/.local/share/nvim/:/root/.local/share/nvim/:rw
      # tmux related
      - ~/.tmux:/root/.tmux:ro
      - ~/.tmux.conf:/root/.tmux.conf:ro
      # git
      - ~/.gitconfig:/root/.gitconfig_local
      # working dirs
      - ./workspace:/root/aerostack2_ws/:rw
    {{ % if privileged % }}
      # dev
      - /dev:/dev:rw
    {{ % endif % }}
    network_mode: "host"
    command: tail -f /dev/null
