version: "3.3"
services:
  ubuntu_basic:
    image: ubuntu:20.04
    container_name: ubuntu_basic
    command: tail -F anything
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    network_mode: "host"
