services:
  mr_scene_mapping:
    image: mr_scene_mapping
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: mr_scene_mapping
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      TERM: xterm-256color
      SHELL: $SHELL
    runtime: nvidia
    privileged: true
    volumes:
      # display related
      - ~/.Xauthority:/root/.Xauthority:rw
      # ssh related
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # working dirs
      - ./workspace:/root/workspace/:rw
    network_mode: "host"
    command: tail -f /dev/null
