services:
  paper_as2:
    image: paper_as2 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paper_as2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      TERM: $TERM
      SHELL: $SHELL
    runtime: nvidia
    privileged: true
    restart: always
    volumes:
      # display related 
      - ~/.Xauthority:/root/.Xauthority:rw
      # ssh related
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # nvim related
      - ~/.config/nvim:/root/.config/nvim:rw
      - ~/.config/coc:/root/.config/coc:rw
      - ~/.config/github-copilot:/root/.config/github-copilot:rw
      - ~/.local/share/nvim/:/root/.local/share/nvim/:rw
      # tmux related
      - ~/.tmux:/root/.tmux:ro
      - ~/.tmux.conf:/root/.tmux.conf:ro
      # git
      - ~/.gitconfig:/root/.gitconfig_local
      # working dirs
      - ./as2_ws/:/root/aerostack2_ws/:rw
      - ./workspace/:/root/workspace/:rw
      - /dev/:/dev
      # - /media/miguel/CVAR_Miguel/wind_measurement/rosbags:/root/rosbags
    network_mode: "host"
    command: tail -f /dev/null
