services:
  aerostack2:
    image: aerostack2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerostack2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      TERM: $TERM
      SHELL: $SHELL
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    privileged: true
    restart: always
    volumes:
      # display related
      - ~/.Xauthority:/root/.Xauthority:rw
      # ssh related
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # working dirs
      - ./workspace:/root/aerostack2_ws/:rw
    network_mode: "host"
    command: tail -f /dev/null
